version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:5173"
    depends_on:
      - backend
    environment:
      - VITE_API_URL=http://localhost:4000

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mvpdb

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
